/**
 * src/features/mood-discovery/constants/tagMoodMap.ts
 *
 * Maps book tags to mood dimensions they support.
 * First mood in array is "primary" (full points), others are "secondary" (half points).
 * Tags are matched case-insensitively.
 *
 * Updated to match actual AudiobookShelf library tags including:
 * - Structured tags (uppercase): Genre Fiction, Action & Adventure, etc.
 * - Lowercase tags (vibes/themes): cozy-fantasy, enemies-to-lovers, etc.
 * - Duration tags: 5-10-hours, under-5-hours, etc.
 */

import { Mood, Pace, Weight, World, LengthPreference } from '../types';

// ============================================
// MOOD MAPPINGS (40 pts dimension)
// ============================================

export const TAG_MOOD_MAP: Record<string, Mood[]> = {
  // ==========================================
  // COMFORT mood
  // ==========================================
  'cozy': ['comfort'],
  'cozy-fantasy': ['comfort', 'escape'],
  'cozy-mystery': ['comfort', 'thrills'],
  'cozy mystery': ['comfort', 'thrills'],
  'comfort read': ['comfort'],
  'comfort': ['comfort'],
  'feel-good': ['comfort', 'laughs'],
  'feel good': ['comfort', 'laughs'],
  'heartwarming': ['comfort', 'feels'],
  'found-family': ['comfort', 'feels'],
  'found family': ['comfort', 'feels'],
  'comfort food': ['comfort'],
  'gentle': ['comfort'],
  'low stakes': ['comfort'],
  'slice of life': ['comfort'],
  'wholesome': ['comfort', 'feels'],
  'hygge': ['comfort'],
  'warm': ['comfort', 'feels'],
  'uplifting': ['comfort', 'feels'],
  'hopeful': ['comfort', 'feels'],
  'hope': ['comfort', 'feels'],
  'healing': ['comfort', 'feels'],
  'easy-listening': ['comfort'],
  'easy listening': ['comfort'],
  'inspiring': ['comfort', 'feels'],
  'friendship': ['comfort', 'feels'],
  'small-town': ['comfort'],
  'small town': ['comfort'],
  'small-town-romance': ['comfort', 'feels'],
  'faith': ['comfort', 'thinking'],
  'family life': ['comfort', 'feels'],
  'women sleuths': ['comfort', 'thrills'],

  // ==========================================
  // THRILLS mood
  // ==========================================
  'thriller': ['thrills'],
  'thriller & suspense': ['thrills'],
  'suspense': ['thrills'],
  'suspenseful': ['thrills'],
  'mystery': ['thrills'],
  'crime': ['thrills'],
  'crime thrillers': ['thrills'],
  'twisty': ['thrills'],
  'page-turner': ['thrills'],
  'page turner': ['thrills'],
  'edge of seat': ['thrills'],
  'unpredictable': ['thrills'],
  'unreliable-narrator': ['thrills', 'thinking'],
  'unreliable narrator': ['thrills', 'thinking'],
  'whodunit': ['thrills'],
  'cat and mouse': ['thrills'],
  'heist': ['thrills', 'laughs'],
  'survival': ['thrills', 'feels'],
  'tense': ['thrills'],
  'gripping': ['thrills'],
  'noir': ['thrills', 'thinking'],
  'detective': ['thrills'],
  'psychological': ['thrills', 'thinking'],
  'psychological thriller': ['thrills', 'thinking'],
  'psychological-horror': ['thrills'],
  'spy': ['thrills', 'escape'],
  'espionage': ['thrills', 'escape'],
  'spies & politics': ['thrills', 'thinking'],
  'action-packed': ['thrills', 'escape'],
  'action packed': ['thrills', 'escape'],
  'action & adventure': ['thrills', 'escape'],
  'domestic-thriller': ['thrills'],
  'domestic thriller': ['thrills'],
  'legal-thriller': ['thrills'],
  'legal thriller': ['thrills'],
  'technothrillers': ['thrills', 'thinking'],
  'cold-case': ['thrills'],
  'cold case': ['thrills'],
  'police-procedural': ['thrills'],
  'police procedural': ['thrills'],
  'mysterious': ['thrills'],
  'haunted-house': ['thrills', 'escape'],
  'haunted house': ['thrills', 'escape'],
  'ghosts': ['thrills', 'escape'],
  'revenge': ['thrills', 'feels'],
  'justice': ['thrills', 'thinking'],
  'romantic suspense': ['thrills', 'feels'],

  // ==========================================
  // ESCAPE mood
  // ==========================================
  'adventure': ['escape', 'thrills'],
  'epic': ['escape'],
  'epic fantasy': ['escape'],
  'quest': ['escape'],
  'world-building': ['escape'],
  'worldbuilding': ['escape'],
  'immersive': ['escape'],
  'escapist': ['escape'],
  'journey': ['escape'],
  'exploration': ['escape'],
  'chosen-one': ['escape'],
  'chosen one': ['escape'],
  'portal-fantasy': ['escape'],
  'portal fantasy': ['escape'],
  'portal': ['escape'],
  'second world': ['escape'],
  'high fantasy': ['escape'],
  'sword and sorcery': ['escape', 'thrills'],
  'space-opera': ['escape', 'thrills'],
  'space opera': ['escape', 'thrills'],
  'space exploration': ['escape'],
  'dragons': ['escape'],
  'dragons & mythical creatures': ['escape'],
  'fae': ['escape', 'feels'],
  'fairy-tale-retelling': ['escape'],
  'fairy tale retelling': ['escape'],
  'fairy tales': ['escape', 'comfort'],
  'prophecy': ['escape'],
  'magic-users': ['escape'],
  'magic users': ['escape'],
  'forest': ['escape'],
  'castle': ['escape'],
  'academy': ['escape'],
  'superhero': ['escape', 'thrills'],
  'underdog': ['escape', 'feels'],
  'reluctant-hero': ['escape', 'thrills'],
  'reluctant hero': ['escape', 'thrills'],
  'whimsical': ['escape', 'laughs'],
  'sagas': ['escape', 'feels'],

  // ==========================================
  // LAUGHS mood
  // ==========================================
  'humor': ['laughs'],
  'humour': ['laughs'],
  'funny': ['laughs'],
  'comedy': ['laughs'],
  'witty': ['laughs'],
  'satire': ['laughs', 'thinking'],
  'absurd': ['laughs'],
  'rom-com': ['laughs', 'comfort'],
  'romcom': ['laughs', 'comfort'],
  'banter': ['laughs', 'comfort'],
  'snarky': ['laughs'],
  'hilarious': ['laughs'],
  'parody': ['laughs'],
  'dry humor': ['laughs', 'thinking'],
  'dark humor': ['laughs', 'thrills'],
  'dark comedy': ['laughs', 'thrills'],
  'grumpy-sunshine': ['laughs', 'comfort'],
  'grumpy sunshine': ['laughs', 'comfort'],

  // ==========================================
  // FEELS mood
  // ==========================================
  'emotional': ['feels'],
  'tearjerker': ['feels'],
  'moving': ['feels'],
  'poignant': ['feels'],
  'bittersweet': ['feels'],
  'grief': ['feels'],
  'family drama': ['feels'],
  'coming-of-age': ['feels', 'escape'],
  'coming of age': ['feels', 'escape'],
  'love story': ['feels', 'comfort'],
  'love': ['feels', 'comfort'],
  'redemption': ['feels'],
  'redemption-arc': ['feels'],
  'redemption arc': ['feels'],
  'emotional journey': ['feels'],
  'loss': ['feels'],
  'family': ['feels', 'comfort'],
  'relationships': ['feels'],
  'heart-wrenching': ['feels'],
  'heartbreaking': ['feels'],
  'beautiful': ['feels'],
  'touching': ['feels'],
  'romantic': ['feels', 'comfort'],
  'romance': ['feels', 'comfort'],
  'sacrifice': ['feels'],
  'loyalty': ['feels', 'comfort'],
  'forgiveness': ['feels', 'comfort'],
  'trauma': ['feels'],
  'mental-health': ['feels', 'thinking'],
  'mental health': ['feels', 'thinking'],
  'self-discovery': ['feels', 'thinking'],
  'self discovery': ['feels', 'thinking'],
  'identity': ['feels', 'thinking'],
  'marriage': ['feels', 'comfort'],

  // ==========================================
  // THINKING mood
  // ==========================================
  'thought-provoking': ['thinking'],
  'thought provoking': ['thinking'],
  'literary': ['thinking'],
  'literary fiction': ['thinking'],
  'philosophical': ['thinking'],
  'philosophy': ['thinking'],
  'complex': ['thinking'],
  'layered': ['thinking'],
  'character study': ['thinking', 'feels'],
  'character-driven': ['thinking', 'feels'],
  'character driven': ['thinking', 'feels'],
  'moral dilemma': ['thinking'],
  'morally-grey': ['thinking'],
  'morally grey': ['thinking'],
  'social commentary': ['thinking'],
  'speculative': ['thinking', 'escape'],
  'cerebral': ['thinking'],
  'introspective': ['thinking', 'feels'],
  'ambitious': ['thinking'],
  'challenging': ['thinking'],
  'mind-bending': ['thinking', 'thrills'],
  'intelligent': ['thinking'],
  'experimental': ['thinking'],
  'dual-timeline': ['thinking'],
  'dual timeline': ['thinking'],
  'antihero': ['thinking', 'thrills'],
  'political': ['thinking', 'thrills'],
  'power': ['thinking', 'escape'],
  'class': ['thinking'],
  'classics': ['thinking'],
  'classic': ['thinking'],
  'award-winner': ['thinking'],
  'award winner': ['thinking'],
  'world literature': ['thinking'],
};

// ============================================
// PACE MAPPINGS (15 pts dimension)
// ============================================

export const TAG_PACE_MAP: Record<string, Pace[]> = {
  // SLOW pace
  'slow-burn': ['slow'],
  'slow burn': ['slow'],
  'contemplative': ['slow'],
  'atmospheric': ['slow'],
  'meandering': ['slow'],
  'literary': ['slow'],
  'meditative': ['slow'],
  'leisurely': ['slow'],
  'character-driven': ['slow'],
  'character driven': ['slow'],
  'quiet': ['slow'],
  'gentle pace': ['slow'],
  'easy-listening': ['slow'],
  'easy listening': ['slow'],

  // STEADY pace
  'well-paced': ['steady'],
  'well paced': ['steady'],
  'balanced': ['steady'],
  'measured': ['steady'],
  'engaging': ['steady'],
  'plot-driven': ['steady'],
  'plot driven': ['steady'],

  // FAST pace
  'fast-paced': ['fast'],
  'fast paced': ['fast'],
  'page-turner': ['fast'],
  'page turner': ['fast'],
  'gripping': ['fast'],
  'action-packed': ['fast'],
  'action packed': ['fast'],
  'unputdownable': ['fast'],
  'relentless': ['fast'],
  'breakneck': ['fast'],
  'propulsive': ['fast'],
  'quick read': ['fast'],
  'compulsive': ['fast'],
  'suspenseful': ['fast'],
};

// ============================================
// WEIGHT MAPPINGS (15 pts dimension)
// ============================================

export const TAG_WEIGHT_MAP: Record<string, Weight[]> = {
  // LIGHT weight
  'light': ['light'],
  'light read': ['light'],
  'beach read': ['light'],
  'easy read': ['light'],
  'easy-listening': ['light'],
  'easy listening': ['light'],
  'fun': ['light'],
  'fluffy': ['light'],
  'low angst': ['light'],
  'lighthearted': ['light'],
  'light-hearted': ['light'],
  'breezy': ['light'],
  'carefree': ['light'],
  'cozy': ['light'],
  'cozy-fantasy': ['light'],
  'cozy-mystery': ['light'],
  'rom-com': ['light'],
  'romcom': ['light'],
  'whimsical': ['light'],
  'hopeful': ['light'],

  // BALANCED weight
  'balanced': ['balanced'],
  'engaging': ['balanced'],
  'moderate': ['balanced'],

  // HEAVY weight
  'dark': ['heavy'],
  'dark-fantasy': ['heavy'],
  'dark fantasy': ['heavy'],
  'dark-romance': ['heavy'],
  'dark romance': ['heavy'],
  'intense': ['heavy'],
  'gritty': ['heavy'],
  'grimdark': ['heavy'],
  'heavy': ['heavy'],
  'brutal': ['heavy'],
  'unflinching': ['heavy'],
  'harrowing': ['heavy'],
  'challenging': ['heavy'],
  'trigger warning': ['heavy'],
  'disturbing': ['heavy'],
  'bleak': ['heavy'],
  'devastating': ['heavy'],
  'raw': ['heavy'],
  'emotional': ['heavy'],
  'difficult': ['heavy'],
  'trauma': ['heavy'],
  'grief': ['heavy'],
  'loss': ['heavy'],
  'heartbreaking': ['heavy'],
  'gothic': ['heavy'],
  'noir': ['heavy'],
  'psychological-horror': ['heavy'],
  'psychological horror': ['heavy'],
  'war': ['heavy'],
  'war & military': ['heavy'],
};

// ============================================
// WORLD MAPPINGS (20 pts dimension)
// ============================================

export const TAG_WORLD_MAP: Record<string, World[]> = {
  // CONTEMPORARY
  'contemporary': ['contemporary'],
  'contemporary fiction': ['contemporary'],
  'contemporary-romance': ['contemporary'],
  'contemporary romance': ['contemporary'],
  'modern': ['contemporary'],
  'present day': ['contemporary'],
  'present-day': ['contemporary'],
  'urban': ['contemporary'],
  'realistic': ['contemporary'],
  'small-town': ['contemporary'],
  'small town': ['contemporary'],
  'small-town-romance': ['contemporary'],
  'modern day': ['contemporary'],
  'real world': ['contemporary'],
  'big-city': ['contemporary'],
  'big city': ['contemporary'],
  'college': ['contemporary'],
  'united states': ['contemporary'],

  // HISTORICAL
  'historical': ['historical'],
  'historical fiction': ['historical'],
  'historical-romance': ['historical'],
  'historical romance': ['historical'],
  'period': ['historical'],
  'regency': ['historical'],
  'victorian': ['historical'],
  'medieval': ['historical'],
  'wwii': ['historical'],
  'wwi': ['historical'],
  'ww2': ['historical'],
  'ww1': ['historical'],
  'world war': ['historical'],
  'ancient': ['historical'],
  '19th century': ['historical'],
  '20th century': ['historical'],
  '18th century': ['historical'],
  '1920s': ['historical'],
  'tudor': ['historical'],
  'civil-war': ['historical'],
  'civil war': ['historical'],
  'renaissance': ['historical'],
  'european': ['historical'],
  'gaslamp': ['historical'],
  'war': ['historical'],

  // FANTASY
  'fantasy': ['fantasy'],
  'science fiction & fantasy': ['fantasy'],
  'magic': ['fantasy'],
  'dragons': ['fantasy'],
  'dragons & mythical creatures': ['fantasy'],
  'fae': ['fantasy'],
  'faerie': ['fantasy'],
  'fairy': ['fantasy'],
  'fairy tales': ['fantasy'],
  'fairy-tale-retelling': ['fantasy'],
  'witches': ['fantasy'],
  'urban-fantasy': ['fantasy'],
  'urban fantasy': ['fantasy'],
  'paranormal & urban': ['fantasy'],
  'epic-fantasy': ['fantasy'],
  'epic fantasy': ['fantasy'],
  'high fantasy': ['fantasy'],
  'low fantasy': ['fantasy'],
  'dark-fantasy': ['fantasy'],
  'dark fantasy': ['fantasy'],
  'cozy-fantasy': ['fantasy'],
  'cozy fantasy': ['fantasy'],
  'fairy tale': ['fantasy'],
  'fairytale': ['fantasy'],
  'mythology': ['fantasy'],
  'mythological': ['fantasy'],
  'magical realism': ['fantasy'],
  'paranormal': ['fantasy'],
  'supernatural': ['fantasy'],
  'wizards': ['fantasy'],
  'elves': ['fantasy'],
  'vampires': ['fantasy'],
  'werewolves': ['fantasy'],
  'shapeshifters': ['fantasy'],
  'magic-users': ['fantasy'],
  'portal-fantasy': ['fantasy'],
  'portal fantasy': ['fantasy'],
  'steampunk': ['fantasy'],
  'gaslamp': ['fantasy'],
  'ghosts': ['fantasy'],
  'forest': ['fantasy'],
  'castle': ['fantasy'],

  // SCIFI
  'sci-fi': ['scifi'],
  'scifi': ['scifi'],
  'science fiction': ['scifi'],
  'science fiction & fantasy': ['scifi'],
  'sf': ['scifi'],
  'space': ['scifi'],
  'space-opera': ['scifi'],
  'space opera': ['scifi'],
  'space exploration': ['scifi'],
  'spaceship': ['scifi'],
  'cyberpunk': ['scifi'],
  'dystopian': ['scifi'],
  'dystopia': ['scifi'],
  'post-apocalyptic': ['scifi'],
  'post apocalyptic': ['scifi'],
  'apocalyptic': ['scifi'],
  'robots': ['scifi'],
  'ai': ['scifi'],
  'artificial intelligence': ['scifi'],
  'genetic engineering': ['scifi'],
  'aliens': ['scifi'],
  'first-contact': ['scifi'],
  'first contact': ['scifi'],
  'futuristic': ['scifi'],
  'time-travel': ['scifi'],
  'time travel': ['scifi'],
  'near future': ['scifi'],
  'far future': ['scifi'],
  'military sci-fi': ['scifi'],
  'military': ['scifi'],
  'hard sci-fi': ['scifi'],
  'hard science fiction': ['scifi'],
  'soft sci-fi': ['scifi'],
  'alternate-history': ['scifi'],
  'alternate history': ['scifi'],
  'technothrillers': ['scifi'],
  'superhero': ['scifi'],
};

// ============================================
// LENGTH MAPPINGS (10 pts dimension) - NEW!
// ============================================

export const TAG_LENGTH_MAP: Record<string, LengthPreference[]> = {
  // SHORT (under 6 hours)
  'under-5-hours': ['short'],
  'under 5 hours': ['short'],
  'quick read': ['short'],
  'novella': ['short'],
  'short': ['short'],

  // MEDIUM (6-12 hours)
  '5-10-hours': ['medium'],
  '5-10 hours': ['medium'],
  '10-15-hours': ['medium'],
  '10-15 hours': ['medium'],

  // LONG (12+ hours)
  '15-20-hours': ['long'],
  '15-20 hours': ['long'],
  'over-20-hours': ['long'],
  'over 20 hours': ['long'],
  'epic': ['long'],
  'sagas': ['long'],
};

// ============================================
// ROMANCE TROPE MAPPINGS (bonus points)
// ============================================

export const TAG_ROMANCE_TROPES: Record<string, Mood[]> = {
  'enemies-to-lovers': ['feels', 'thrills'],
  'enemies to lovers': ['feels', 'thrills'],
  'friends-to-lovers': ['comfort', 'feels'],
  'friends to lovers': ['comfort', 'feels'],
  'second-chance': ['feels'],
  'second chance': ['feels'],
  'second chance romance': ['feels'],
  'fake-relationship': ['laughs', 'comfort'],
  'fake relationship': ['laughs', 'comfort'],
  'fake dating': ['laughs', 'comfort'],
  'forced-proximity': ['comfort', 'thrills'],
  'forced proximity': ['comfort', 'thrills'],
  'grumpy-sunshine': ['laughs', 'comfort'],
  'grumpy sunshine': ['laughs', 'comfort'],
  'grumpy/sunshine': ['laughs', 'comfort'],
  'only one bed': ['laughs', 'comfort'],
  'marriage of convenience': ['feels', 'comfort'],
  'forbidden-love': ['feels', 'thrills'],
  'forbidden love': ['feels', 'thrills'],
  'forbidden romance': ['feels', 'thrills'],
  'soulmates': ['feels', 'comfort'],
  'fated mates': ['feels', 'escape'],
  'slow-burn': ['feels', 'comfort'],
  'slow burn': ['feels', 'comfort'],
  'instalove': ['escape'],
  'love triangle': ['feels', 'thrills'],
  'arranged marriage': ['feels', 'comfort'],
  'opposites attract': ['laughs', 'comfort'],
  'best friends brother': ['feels', 'comfort'],
  'office romance': ['comfort', 'laughs'],
  'workplace romance': ['comfort', 'laughs'],
  'age gap': ['feels'],
  'reverse harem': ['escape', 'feels'],
  'single parent': ['feels', 'comfort'],
  'billionaire': ['escape'],
  'royalty': ['escape', 'feels'],
  'paranormal-romance': ['escape', 'feels'],
  'paranormal romance': ['escape', 'feels'],
  'dark-romance': ['feels', 'thrills'],
  'dark romance': ['feels', 'thrills'],
  'contemporary-romance': ['comfort', 'feels'],
  'contemporary romance': ['comfort', 'feels'],
  'small-town-romance': ['comfort', 'feels'],
  'small town romance': ['comfort', 'feels'],
  'historical-romance': ['feels', 'escape'],
  'historical romance': ['feels', 'escape'],
};
