/**
 * src/features/player/constants/index.ts
 *
 * Player constants exports.
 */

export {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  COVER_SIZE,
  ACCENT_COLOR,
  SPEED_QUICK_OPTIONS,
  SLEEP_QUICK_OPTIONS,
  TIMELINE_WIDTH,
  TIMELINE_HEIGHT,
  TIMELINE_MARKER_RADIUS,
  TIMELINE_MAJOR_TICK_HEIGHT,
  TIMELINE_MINOR_TICK_HEIGHT,
  CHAPTER_MARKER_X,
  CHAPTER_MARKER_CIRCLE_SIZE,
  CHAPTER_TICK_HEIGHT,
  TEN_MIN_TICK_HEIGHT,
  ONE_MIN_TICK_HEIGHT,
  FIFTEEN_SEC_TICK_HEIGHT,
  CHAPTER_LABEL_Y,
  MINUTES_PER_SCREEN,
  PIXELS_PER_SECOND,
  CHAPTER_TIMELINE_TOTAL_HEIGHT,
  CHAPTER_TICKS_AREA_HEIGHT,
  CHAPTER_MARKER_LINE_HEIGHT,
  EDGE_ZONE,
  SPEED_MODE_LABELS,
  BOOKMARK_FLAG_PENNANT_WIDTH,
  BOOKMARK_FLAG_PENNANT_HEIGHT,
  BOOKMARK_FLAG_POLE_WIDTH,
  BOOKMARK_FLAG_COLOR,
  BOOKMARK_STEM_COLOR,
} from './playerConstants';
